In [4]:
import numpy as np

x = np.random.randint(10000,size=(5000))
x.shape

(5000,)

In [5]:
y=[]
for i in x:
    if i%2==0:  #2,3,5,7,10
        y.append(1)
    else:
        y.append(0)
y=np.array(y)

In [20]:
x

array([[1324],
       [7132],
       [2110],
       ...,
       [ 956],
       [2372],
       [3517]])

In [21]:
y

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [8]:
x=x.reshape(-1,1)
y=y.reshape(-1,1)



In [9]:
print(x)
print(y)


[[1324]
 [7132]
 [2110]
 ...
 [ 956]
 [2372]
 [3517]]
[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [0]]


In [10]:
print(x.shape)
print(y.shape)

(5000, 1)
(5000, 1)


In [11]:
y=y.reshape(-1,1)
y

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [12]:
x_train=[]
x_test=[]
y_train=[]
y_test=[]


In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [24]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


(3350, 1)
(1650, 1)
(3350, 1)
(1650, 1)


In [45]:
import keras 

import numpy as np


from keras.models import Sequential

model = Sequential()
from keras.layers import Dense,Activation
from keras.optimizers import SGD,Adam

model.add(Dense(units=12, input_dim=1,init='uniform',activation='relu'))
model.add(Dense(units=8, init='uniform',activation='relu'))
model.add(Dense(activation='sigmoid',units=1))

C:\Users\tamilselvan\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=12, input_dim=1, activation="relu", kernel_initializer="uniform")`
  if sys.path[0] == '':
C:\Users\tamilselvan\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=8, activation="relu", kernel_initializer="uniform")`
  del sys.path[0]


In [46]:
# compile model
model.compile(loss='mean_squared_error', optimizer=Adam(),metrics=['accuracy'])

In [47]:

model.fit(x_train, y_train, epochs=50,batch_size=4)

Epoch 1/50
3350/3350 [==============================] - 2s 616us/step - loss: 0.2692 - acc: 0.4943
Epoch 2/50
3350/3350 [==============================] - 1s 340us/step - loss: 0.2500 - acc: 0.5116
Epoch 3/50
3350/3350 [==============================] - 1s 331us/step - loss: 0.2500 - acc: 0.5116
Epoch 4/50
3350/3350 [==============================] - 1s 334us/step - loss: 0.2499 - acc: 0.5116
Epoch 5/50
3350/3350 [==============================] - 1s 393us/step - loss: 0.2500 - acc: 0.5116
Epoch 6/50
3350/3350 [==============================] - 1s 347us/step - loss: 0.2499 - acc: 0.5116
Epoch 7/50
3350/3350 [==============================] - 1s 356us/step - loss: 0.2499 - acc: 0.5116
Epoch 8/50
3350/3350 [==============================] - 1s 356us/step - loss: 0.2499 - acc: 0.5116
Epoch 9/50
3350/3350 [==============================] - 1s 362us/step - loss: 0.2499 - acc: 0.5116
Epoch 10/50
3350/3350 [==============================] - 1s 344us/step - loss: 0.2499 - acc: 0.5116
Epoch 11/

In [140]:
x[500]

4660

In [139]:
y[500]

1

In [206]:
y

array([[0],
       [1],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [164]:
clas= []

In [135]:

y=np.array(clas)
len(clas)

5000

In [167]:
y.shape

(5000, 1)

In [166]:
len(clas)

5000

In [165]:
for i in x:
    if i%2==0:  #2,3,5,7,10
        clas.append(1)
    else:
        clas.append(0)


In [3]:
y_train = keras.utils.to_categorical(clas, num_classes=11)

NameError: name 'keras' is not defined

In [31]:
# Regression Example With Boston Dataset: Baseline
from numpy import loadtxt
import pandas as pd 
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.metrics import  accuracy_score
# load dataset

In [26]:
x_train.reshape(-1,1)

array([[9059],
       [8087],
       [6905],
       ...,
       [3550],
       [5120],
       [ 905]])

In [27]:
y_train

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [0]])

In [28]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression()
logisticRegr.fit(x_train.reshape(-1,1), y_train.reshape(-1,1))


C:\Users\tamilselvan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\tamilselvan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [36]:
pred=logisticRegr.predict(x_test.reshape(-1,1))

array([1, 0, 1, ..., 0, 0, 0])

In [223]:
x_test

array([4303, 1881, 3960, ..., 3354, 7015, 7925])

In [ ]:
lol1.s

In [37]:
y_test

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]])

In [224]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, max_depth=2,
                            random_state=0)

In [225]:
clf.fit(x_train.reshape(-1,1), y_train.reshape(-1,1))

C:\Users\tamilselvan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [34]:
 clf.predict(x_test.reshape(-1,1))

NameError: name 'clf' is not defined

In [38]:
accuracy_score(y_test,pred)

0.526060606060606