In [577]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
x_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(np.random.randint(5, size=(10, 2)), num_classes=10)
x_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)



In [866]:
x_train

array([[0.38132647, 0.31751938, 0.72615332, ..., 0.02178419, 0.80614257,
        0.89121967],
       [0.6452941 , 0.07093006, 0.03469143, ..., 0.11689184, 0.72309706,
        0.82970292],
       [0.63738563, 0.94170479, 0.75411451, ..., 0.17834658, 0.34835758,
        0.97326111],
       ...,
       [0.64024234, 0.32336987, 0.63225632, ..., 0.29171983, 0.452593  ,
        0.57840098],
       [0.24277825, 0.63437181, 0.96525699, ..., 0.56694329, 0.98372522,
        0.86533916],
       [0.92038721, 0.64808784, 0.16810469, ..., 0.87984733, 0.67330049,
        0.19730262]])

In [903]:
x_train = np.random.randint(10000, size=(5000))

x_train.shape

(5000,)

In [902]:
clas= []

In [904]:
for i in x_train:
    if i%10==0:  #2,3,5,7,10
        clas.append(10)
    elif i%7==0:
        clas.append(7)
    elif i%5==0:
        clas.append(5)
    elif i%3==0:
        clas.append(3)
    elif i%2==0:
        clas.append(2)
    else:
        clas.append(0)

    
y_train = keras.utils.to_categorical(clas, num_classes=11)
x_train=np.array(x_train).reshape(-1,1)
y_train
    

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [908]:
x_train

array([[2042],
       [1149],
       [8351],
       ...,
       [9733],
       [1966],
       [8297]])

In [843]:
lol

array([ 240, 9305, 7071, ..., 7307, 8587, 5947])

In [837]:
6266/7

895.1428571428571

In [909]:
from sklearn.model_selection import train_test_split

In [910]:
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.33, random_state=42)

In [912]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(3350, 1)
(3350, 11)
(1650, 1)
(1650, 11)


In [ ]:
clas= []

In [ ]:
y_train = np.random.randint(10000, size=(5000))

x_train.shape

In [ ]:
for i in x_train:
    if i%10==0:  #2,3,5,7,10
        clas.append(10)
    elif i%7==0:
        clas.append(7)
    elif i%5==0:
        clas.append(5)
    elif i%3==0:
        clas.append(3)
    elif i%2==0:
        clas.append(2)
    else:
        clas.append(0)

    
y_train = keras.utils.to_categorical(clas, num_classes=11)
x_train=np.array(x_train).reshape(-1,1)
y_train
    

In [ ]:
clas

In [846]:
y_train = keras.utils.to_categorical(clas, num_classes=11)

In [847]:
y_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [865]:
y_train[1056]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [863]:
clas=np.array(clas)

In [864]:
clas

array([10,  5,  3, ...,  0,  0,  0])

In [860]:
clas[1056]

3

In [56]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1000, 20)
(1000, 10)
(100, 20)
(100, 10)


In [66]:
import numpy as np
np.argmax(y_train[3])

4

In [310]:
np.random.randint(10, size=(10, 2))*5

array([[ 5,  0],
       [30,  5],
       [ 5,  5],
       [15,  5],
       [15, 45],
       [25,  5],
       [35, 45],
       [ 0, 45],
       [ 5, 30],
       [20, 30]])

In [309]:
y_train = keras.utils.to_categorical(lol, num_classes=10)
y_train

array([[[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0

In [307]:
y_train.reshape(-1,1).shape

(300, 1)

In [575]:
lol = np.random.randint(100, size=(10, 3))*2

lol

array([[172, 190,  66],
       [  4, 188, 166],
       [156, 112,  42],
       [ 96, 178, 130],
       [  0,  32,  98],
       [ 22,  30, 146],
       [114, 184,  92],
       [ 48, 180, 128],
       [174,  60, 102],
       [140, 198, 138]])

In [179]:
np.random.randint(5, size=(10, 2))

array([[1, 0],
       [2, 2],
       [0, 4],
       [2, 2],
       [0, 1],
       [0, 2],
       [2, 1],
       [2, 3],
       [0, 4],
       [1, 3]])

In [178]:
np.random.random((10, 2))

array([[0.94514874, 0.24968624],
       [0.27389186, 0.24517419],
       [0.23078986, 0.95295065],
       [0.89149046, 0.80691251],
       [0.33444986, 0.58823608],
       [0.19342345, 0.61050008],
       [0.15138137, 0.86399851],
       [0.16032578, 0.87533366],
       [0.85219085, 0.1515932 ],
       [0.61211151, 0.08827328]])

In [68]:
lol= y_train.reshape(-1,1)

In [75]:
lol.shape

(10000, 1)

In [72]:
lol

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]], dtype=float32)

In [80]:
x_train = np.random.random((2, 2))

In [81]:
x_train

array([[0.20668437, 0.37950902],
       [0.77299447, 0.03085404]])

In [79]:
x_train

array([[0.60678734, 0.80058908]])

In [933]:
import keras
import tensorflow as tf
from keras.optimizers import SGD


In [932]:
model = Sequential()


In [934]:

# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(16, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))



In [935]:
sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])


In [936]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_20 (Dense)             (None, 16)                336       
_________________________________________________________________
dropout_13 (Dropout)         (None, 16)                0         
_________________________________________________________________
dense_21 (Dense)             (None, 32)                544       
_________________________________________________________________
dropout_14 (Dropout)         (None, 32)                0         
_________________________________________________________________
dense_22 (Dense)             (None, 10)                330       
Total params: 1,210
Trainable params: 1,210
Non-trainable params: 0
_________________________________________________________________


In [37]:
score = model.evaluate(x_test, y_test, batch_size=128)

100/100 [==============================] - 0s 20us/step


In [38]:
score

[2.305629014968872, 0.14000000059604645]

In [53]:
y_test

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

In [972]:
import tensorflow as tf
model= tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation = tf.nn.softmax))





numpy.ndarray

In [976]:
model.compile(optimizer='adam',
    loss='sparse_categorical_crossentropy',metrics = ['accuracy'])
model.fit(x_train, y_train, epochs=100,batch_size=15)


ValueError: ('Error when checking model target: expected no data, but got:', array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32))

In [951]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(3350, 1)
(3350, 11)
(1650, 1)
(1650, 11)


In [1003]:
import keras 

import numpy as np


from keras.models import Sequential

model = Sequential()
from keras.layers import Dense,Activation
from keras.optimizers import SGD,Adam

model.add(Dense(units=16, input_dim=1))
model.add(Activation(activation='relu'))
model.add(Dense(units=8))
model.add(Activation(activation='relu'))
model.add(Dense(units=18))
model.add(Activation(activation='relu'))
model.add(Dense(activation='softmax',units=11))

In [1004]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_103 (Dense)            (None, 16)                32        
_________________________________________________________________
activation_62 (Activation)   (None, 16)                0         
_________________________________________________________________
dense_104 (Dense)            (None, 8)                 136       
_________________________________________________________________
activation_63 (Activation)   (None, 8)                 0         
_________________________________________________________________
dense_105 (Dense)            (None, 18)                162       
_________________________________________________________________
activation_64 (Activation)   (None, 18)                0         
_________________________________________________________________
dense_106 (Dense)            (None, 11)                209       
Total para

In [1005]:
# compile model
model.compile(loss='categorical_crossentropy', optimizer=Adam(),metrics=['accuracy'])

In [1006]:
model.fit(x_train, y_train, epochs=100,batch_size=10 )

Epoch 1/100
3350/3350 [==============================] - 2s 484us/step - loss: 8.7613 - acc: 0.2251
Epoch 2/100
3350/3350 [==============================] - 0s 142us/step - loss: 4.4524 - acc: 0.2125
Epoch 3/100
3350/3350 [==============================] - 0s 137us/step - loss: 2.2340 - acc: 0.1949
Epoch 4/100
3350/3350 [==============================] - 0s 138us/step - loss: 2.0258 - acc: 0.2057
Epoch 5/100
3350/3350 [==============================] - 0s 137us/step - loss: 1.9811 - acc: 0.2104
Epoch 6/100
3350/3350 [==============================] - 0s 136us/step - loss: 1.9371 - acc: 0.2176
Epoch 7/100
3350/3350 [==============================] - 1s 153us/step - loss: 1.8794 - acc: 0.2134
Epoch 8/100
3350/3350 [==============================] - 1s 166us/step - loss: 1.9019 - acc: 0.2215
Epoch 9/100
3350/3350 [==============================] - 1s 169us/step - loss: 1.7884 - acc: 0.2296
Epoch 10/100
3350/3350 [==============================] - 0s 146us/step - loss: 1.7370 - acc: 0.2287

In [ ]:
model.fit(x_train,y_train,epochs=3)