In [140]:
import numpy as np 
import matplotlib.pyplot as plt 

In [141]:
import pandas as pd

In [142]:
data = pd.read_csv("C:\\Users\\tamilselvan\\Music\\Google_Stock_Price_Train.csv")

In [245]:
data

Date    Open    High     Low   Close      Volume
0       1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1       1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2       1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3       1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4       1/9/2012  322.04  322.29  309.46  620.76  11,688,800
...          ...     ...     ...     ...     ...         ...
1253  12/23/2016  790.90  792.74  787.28  789.91     623,400
1254  12/27/2016  790.68  797.86  787.66  791.55     789,100
1255  12/28/2016  793.70  794.23  783.20  785.05   1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79     744,300
1257  12/30/2016  782.75  782.78  770.41  771.82   1,770,000

[1258 rows x 6 columns]

In [143]:
train_set = data.iloc[:,1:2].values

In [144]:
train_set 

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

In [145]:
from sklearn.preprocessing import MinMaxScaler

In [146]:
sc= MinMaxScaler(feature_range= (0,1))


In [147]:
train_Scaled= sc.fit_transform(train_set)

In [148]:
train_Scaled

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

In [149]:
x_train=[]
y_train=[]
for i in range(60,1258 ):
    x_train.append(train_Scaled[i-60:i,0])
    y_train.append(train_Scaled[i,0])


In [150]:
train_Scaled[60-60:60,0]

array([0.08581368, 0.09701243, 0.09433366, 0.09156187, 0.07984225,
       0.0643277 , 0.0585423 , 0.06568569, 0.06109085, 0.06639259,
       0.0614257 , 0.07474514, 0.02797827, 0.02379269, 0.02409033,
       0.0159238 , 0.01078949, 0.00967334, 0.01642607, 0.02100231,
       0.02280676, 0.02273235, 0.02810849, 0.03212665, 0.0433812 ,
       0.04475779, 0.04790163, 0.0440695 , 0.04648783, 0.04745517,
       0.04873875, 0.03936305, 0.04137213, 0.04034898, 0.04784582,
       0.04325099, 0.04356723, 0.04286033, 0.04602277, 0.05398467,
       0.05738894, 0.05714711, 0.05569611, 0.04421832, 0.04514845,
       0.04605997, 0.04412531, 0.03675869, 0.04486941, 0.05065481,
       0.05214302, 0.05612397, 0.05818885, 0.06540665, 0.06882953,
       0.07243843, 0.07993526, 0.07846566, 0.08034452, 0.08497656])

In [151]:
train_Scaled

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

In [152]:
X_train,Y_train= np.array(x_train), np.array(y_train)


In [153]:
X_train

array([[0.08581368, 0.09701243, 0.09433366, ..., 0.07846566, 0.08034452,
        0.08497656],
       [0.09701243, 0.09433366, 0.09156187, ..., 0.08034452, 0.08497656,
        0.08627874],
       [0.09433366, 0.09156187, 0.07984225, ..., 0.08497656, 0.08627874,
        0.08471612],
       ...,
       [0.92106928, 0.92438053, 0.93048218, ..., 0.95475854, 0.95204256,
        0.95163331],
       [0.92438053, 0.93048218, 0.9299055 , ..., 0.95204256, 0.95163331,
        0.95725128],
       [0.93048218, 0.9299055 , 0.93113327, ..., 0.95163331, 0.95725128,
        0.93796041]])

In [154]:
X_train= np.reshape(X_train,(X_train.shape[0],X_train.shape[1],1))

In [155]:
X_train

array([[[0.08581368],
        [0.09701243],
        [0.09433366],
        ...,
        [0.07846566],
        [0.08034452],
        [0.08497656]],

       [[0.09701243],
        [0.09433366],
        [0.09156187],
        ...,
        [0.08034452],
        [0.08497656],
        [0.08627874]],

       [[0.09433366],
        [0.09156187],
        [0.07984225],
        ...,
        [0.08497656],
        [0.08627874],
        [0.08471612]],

       ...,

       [[0.92106928],
        [0.92438053],
        [0.93048218],
        ...,
        [0.95475854],
        [0.95204256],
        [0.95163331]],

       [[0.92438053],
        [0.93048218],
        [0.9299055 ],
        ...,
        [0.95204256],
        [0.95163331],
        [0.95725128]],

       [[0.93048218],
        [0.9299055 ],
        [0.93113327],
        ...,
        [0.95163331],
        [0.95725128],
        [0.93796041]]])

In [156]:
Y_train

array([0.08627874, 0.08471612, 0.07454052, ..., 0.95725128, 0.93796041,
       0.93688146])

In [158]:
from keras.models import Sequential
from keras.layers import Dense 
from keras.layers import LSTM
from keras.layers import Dropout

In [159]:
X_train.shape

(1198, 60, 1)

In [160]:
regressor = Sequential()

In [161]:
regressor.add(LSTM(units=50,return_sequences=True,input_shape= (X_train.shape[1],1)))

In [162]:
regressor.add(Dropout(0.2))

In [163]:
regressor.add(LSTM(units= 50,return_sequences=True))
regressor.add(Dropout(0.2))

In [164]:
regressor.add(LSTM(units= 50,return_sequences=True))
regressor.add(Dropout(0.2))

In [165]:
regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

In [166]:
regressor.add(Dense(units = 1))

In [167]:
regressor.compile(optimizer = 'adam',loss= 'mean_squared_error')

In [168]:
regressor.fit(X_train,Y_train,epochs=100,batch_size=32)

Epoch 1/100
1198/1198 [==============================] - 5s 4ms/step - loss: 0.0508
Epoch 2/100
1198/1198 [==============================] - 4s 3ms/step - loss: 0.0059
Epoch 3/100
1198/1198 [==============================] - 4s 3ms/step - loss: 0.0056A: 1s
Epoch 4/100
1198/1198 [==============================] - 4s 3ms/step - loss: 0.0051
Epoch 5/100
1198/1198 [==============================] - 4s 3ms/step - loss: 0.0054
Epoch 6/100
1198/1198 [==============================] - 5s 5ms/step - loss: 0.0048
Epoch 7/100
1198/1198 [==============================] - 5s 4ms/step - loss: 0.0059
Epoch 8/100
1198/1198 [==============================] - 5s 4ms/step - loss: 0.0043
Epoch 9/100
1198/1198 [==============================] - 6s 5ms/step - loss: 0.0046
Epoch 10/100
1198/1198 [==============================] - 5s 4ms/step - loss: 0.0052
Epoch 11/100
1198/1198 [==============================] - 5s 4ms/step - loss: 0.0043
Epoch 12/100
1198/1198 [==============================] - 7s 5ms/step

1198/1198 [==============================] - 7s 5ms/step - loss: 0.0016A: 2s -
Epoch 98/100
1198/1198 [==============================] - 8s 7ms/step - loss: 0.0015
Epoch 99/100
1198/1198 [==============================] - 6s 5ms/step - loss: 0.0015
Epoch 100/100
1198/1198 [==============================] - 7s 6ms/step - loss: 0.0012


In [174]:
Test_data1 = pd.read_csv("C:\\Users\\tamilselvan\\Music\\Google_Stock_Price_Test.csv")

In [176]:
Test_data = Test_data1.iloc[:,1:2].values

In [228]:
Test_data1

Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1    1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2    1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3    1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4    1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5   1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6   1/11/2017  805.00  808.15  801.37  807.91  1,065,900
7   1/12/2017  807.14  807.39  799.17  806.36  1,353,100
8   1/13/2017  807.48  811.22  806.69  807.88  1,099,200
9   1/17/2017  807.08  807.14  800.37  804.61  1,362,100
10  1/18/2017  805.81  806.21  800.99  806.07  1,294,400
11  1/19/2017  805.12  809.48  801.80  802.17    919,300
12  1/20/2017  806.91  806.91  801.69  805.02  1,670,000
13  1/23/2017  807.25  820.87  803.74  819.31  1,963,600
14  1/24/2017  822.30  825.90  817.82  823.87  1,474,000
15  1/25/2017  829.62  835.77  825.06  835.67  1,494,500
16  1/26/2017  837.81  838.00  827.01  832.15  2,973,900
17  1/27/2017  834.71  841.95  820.44  823.31  2,965,800
18  1/30/2017  814.66  815.84  799.80  802.32  3,246,600
19  1/31/2017  796.86  801.25  790.52  796.79  2,160,600

In [235]:
data_total=pd.concat((data['Open'],Test_data1['Open']),axis=0)

In [236]:
data_total

0     325.25
1     331.27
2     329.83
3     328.34
4     322.04
       ...  
15    829.62
16    837.81
17    834.71
18    814.66
19    796.86
Name: Open, Length: 1278, dtype: float64

In [237]:
len(data_total)

1278

In [244]:
len(data_total) - len(Test_data1) - 60

1198

In [238]:
len(data_total[len(data_total) - len(Test_data1) - 60:])

80

In [239]:
inputs=data_total[len(data_total) - len(Test_data1) - 60:].values

In [240]:
inputs.shape

(80,)

In [241]:
inputs = inputs.reshape(-1,1)

In [243]:
inputs

array([[779.  ],
       [779.66],
       [777.71],
       [786.66],
       [783.76],
       [781.22],
       [781.65],
       [779.8 ],
       [787.85],
       [798.24],
       [803.3 ],
       [795.  ],
       [804.9 ],
       [816.68],
       [806.34],
       [801.  ],
       [808.35],
       [795.47],
       [782.89],
       [778.2 ],
       [767.25],
       [750.66],
       [774.5 ],
       [783.4 ],
       [779.94],
       [791.17],
       [756.54],
       [755.6 ],
       [746.97],
       [755.2 ],
       [766.92],
       [771.37],
       [762.61],
       [772.63],
       [767.73],
       [764.26],
       [760.  ],
       [771.53],
       [770.07],
       [757.44],
       [744.59],
       [757.71],
       [764.73],
       [761.  ],
       [772.48],
       [780.  ],
       [785.04],
       [793.9 ],
       [797.4 ],
       [797.34],
       [800.4 ],
       [790.22],
       [796.76],
       [795.84],
       [792.36],
       [790.9 ],
       [790.68],
       [793.7 ],
       [783.33

In [242]:
inputs.shape

(80, 1)

In [211]:
inputs = sc.transform(inputs)
x_test=[]

In [214]:
for i in range(60,80):
    x_test.append(inputs[i-60:i,0])


In [215]:
x_test = np.array(x_test)



TypeError: only integer scalar arrays can be converted to a scalar index

In [217]:
x_test= np.reshape(x_test,(x_test.shape[0],x_test.shape[1],1))

In [218]:
predicted_stocks = regressor.predict(x_test)
predicted_stocks_price=sc.inverse_transform(predicted_stocks)

In [226]:
for i in zip(Test_data1['Open'],predicted_stocks_price):
    print(i)

(778.81, array([795.7138], dtype=float32))
(788.36, array([793.1652], dtype=float32))
(786.08, array([793.406], dtype=float32))
(795.26, array([794.6033], dtype=float32))
(806.4, array([797.65265], dtype=float32))
(807.86, array([802.98895], dtype=float32))
(805.0, array([807.7772], dtype=float32))
(807.14, array([809.7338], dtype=float32))
(807.48, array([810.2092], dtype=float32))
(807.08, array([810.24243], dtype=float32))
(805.81, array([810.33124], dtype=float32))
(805.12, array([810.419], dtype=float32))
(806.91, array([810.52246], dtype=float32))
(807.25, array([811.1561], dtype=float32))
(822.3, array([812.0226], dtype=float32))
(829.62, array([816.2118], dtype=float32))
(837.81, array([822.32526], dtype=float32))
(834.71, array([828.9157], dtype=float32))
(814.66, array([832.44086], dtype=float32))
(796.86, array([828.72345], dtype=float32))


In [223]:
predicted_stocks

array([[0.9609976 ],
       [0.9562565 ],
       [0.9567044 ],
       [0.9589317 ],
       [0.96460426],
       [0.9745312 ],
       [0.9834386 ],
       [0.9870784 ],
       [0.9879627 ],
       [0.9880245 ],
       [0.9881897 ],
       [0.988353  ],
       [0.9885454 ],
       [0.9897243 ],
       [0.9913361 ],
       [0.99912906],
       [1.0105016 ],
       [1.0227616 ],
       [1.0293193 ],
       [1.022404  ]], dtype=float32)

In [224]:
Test_data1

Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1    1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2    1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3    1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4    1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5   1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6   1/11/2017  805.00  808.15  801.37  807.91  1,065,900
7   1/12/2017  807.14  807.39  799.17  806.36  1,353,100
8   1/13/2017  807.48  811.22  806.69  807.88  1,099,200
9   1/17/2017  807.08  807.14  800.37  804.61  1,362,100
10  1/18/2017  805.81  806.21  800.99  806.07  1,294,400
11  1/19/2017  805.12  809.48  801.80  802.17    919,300
12  1/20/2017  806.91  806.91  801.69  805.02  1,670,000
13  1/23/2017  807.25  820.87  803.74  819.31  1,963,600
14  1/24/2017  822.30  825.90  817.82  823.87  1,474,000
15  1/25/2017  829.62  835.77  825.06  835.67  1,494,500
16  1/26/2017  837.81  838.00  827.01  832.15  2,973,900
17  1/27/2017  834.71  841.95  820.44  823.31  2,965,800
18  1/30/2017  814.66  815.84  799.80  802.32  3,246,600
19  1/31/2017  796.86  801.25  790.52  796.79  2,160,600