In [1]:
"RAmesh"

'RAmesh'

In [2]:
  
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.utils import np_utils

Using TensorFlow backend.


In [6]:
data = open("Othello.txt").read().lower()
data

"her father loved me, oft invited me;\nstill questioned me the story of my life\nfrom year to year -- the battles, sieges, fortunes\nthat i have passed.\ni ran it through, even from my boyish days\nto th' very moment that he bade me tell it.\nwherein i spoke of most disastrous chances,\nof moving accidents by flood and field;\nof hairbreadth scapes i' the' imminent deadly breach;\nof being taken by the insolent foe\nand sold to slavery; of my redemption thence\nand portance in my travels' history;\nwherein of anters vast and deserts idle,\nrough quarries, rocks, and hills whose heads touch heaven,\nit was my hint to speak -- such was the process;\nand of the cannibals that each other eat,\nthe anthropophagi, and men whose heads\ndo grow beneath their shoulders. this to hear\nwould desdemona seriously incline;\nbut still the house affairs would draw her thence;\nwhich ever she could with haste dispatch,\nshe'd come again, and with a greedy ear\ndevour up my discourse. which i observing,

In [17]:
len(data)

1860

In [7]:
chars = sorted(list(set(data)))
chars

['\n',
 ' ',
 "'",
 ',',
 '-',
 '.',
 ';',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'y']

In [9]:
totalChars = len(data)
totalChars

1860

In [10]:
numberOfUniqueChars = len(chars)
numberOfUniqueChars

30

In [11]:
CharsForids = {char:Id for Id, char in enumerate(chars)}
CharsForids

{'\n': 0,
 ' ': 1,
 "'": 2,
 ',': 3,
 '-': 4,
 '.': 5,
 ';': 6,
 'a': 7,
 'b': 8,
 'c': 9,
 'd': 10,
 'e': 11,
 'f': 12,
 'g': 13,
 'h': 14,
 'i': 15,
 'k': 16,
 'l': 17,
 'm': 18,
 'n': 19,
 'o': 20,
 'p': 21,
 'q': 22,
 'r': 23,
 's': 24,
 't': 25,
 'u': 26,
 'v': 27,
 'w': 28,
 'y': 29}

In [12]:
idsForChars = {Id:char for Id, char in enumerate(chars)}
idsForChars

{0: '\n',
 1: ' ',
 2: "'",
 3: ',',
 4: '-',
 5: '.',
 6: ';',
 7: 'a',
 8: 'b',
 9: 'c',
 10: 'd',
 11: 'e',
 12: 'f',
 13: 'g',
 14: 'h',
 15: 'i',
 16: 'k',
 17: 'l',
 18: 'm',
 19: 'n',
 20: 'o',
 21: 'p',
 22: 'q',
 23: 'r',
 24: 's',
 25: 't',
 26: 'u',
 27: 'v',
 28: 'w',
 29: 'y'}

In [14]:
numberOfCharsToLearn = 100
numberOfCharsToLearn

100

In [15]:
counter = totalChars - numberOfCharsToLearn
counter

1760

In [ ]:
for i in data[1:1+100]:
    print(i)

In [40]:
#Inpput data
charX = []
#output data
y = []
for i in range(0, counter, 1):
    theInputChars = data[i:i+numberOfCharsToLearn]
    theOutputChars = data[i + numberOfCharsToLearn]
    charX.append([CharsForids[char] for char in theInputChars])
    y.append(CharsForids[theOutputChars])

X = np.reshape(charX, (len(charX), numberOfCharsToLearn, 1))


X = X/float(numberOfUniqueChars)
print(y)

y = np_utils.to_categorical(y)
print(y)



[14, 11, 1, 8, 7, 25, 25, 17, 11, 24, 3, 1, 24, 15, 11, 13, 11, 24, 3, 1, 12, 20, 23, 25, 26, 19, 11, 24, 0, 25, 14, 7, 25, 1, 15, 1, 14, 7, 27, 11, 1, 21, 7, 24, 24, 11, 10, 5, 0, 15, 1, 23, 7, 19, 1, 15, 25, 1, 25, 14, 23, 20, 26, 13, 14, 3, 1, 11, 27, 11, 19, 1, 12, 23, 20, 18, 1, 18, 29, 1, 8, 20, 29, 15, 24, 14, 1, 10, 7, 29, 24, 0, 25, 20, 1, 25, 14, 2, 1, 27, 11, 23, 29, 1, 18, 20, 18, 11, 19, 25, 1, 25, 14, 7, 25, 1, 14, 11, 1, 8, 7, 10, 11, 1, 18, 11, 1, 25, 11, 17, 17, 1, 15, 25, 5, 0, 28, 14, 11, 23, 11, 15, 19, 1, 15, 1, 24, 21, 20, 16, 11, 1, 20, 12, 1, 18, 20, 24, 25, 1, 10, 15, 24, 7, 24, 25, 23, 20, 26, 24, 1, 9, 14, 7, 19, 9, 11, 24, 3, 0, 20, 12, 1, 18, 20, 27, 15, 19, 13, 1, 7, 9, 9, 15, 10, 11, 19, 25, 24, 1, 8, 29, 1, 12, 17, 20, 20, 10, 1, 7, 19, 10, 1, 12, 15, 11, 17, 10, 6, 0, 20, 12, 1, 14, 7, 15, 23, 8, 23, 11, 7, 10, 25, 14, 1, 24, 9, 7, 21, 11, 24, 1, 15, 2, 1, 25, 14, 11, 2, 1, 15, 18, 18, 15, 19, 11, 19, 25, 1, 10, 11, 7, 10, 17, 29, 1, 8, 23, 11, 7, 9, 14

In [34]:
X = np.reshape(charX, (len(charX), numberOfCharsToLearn, 1))


In [36]:
X.shape

(1760, 100, 1)

In [37]:
X

array([[[14],
        [11],
        [23],
        ...,
        [ 4],
        [ 1],
        [25]],

       [[11],
        [23],
        [ 1],
        ...,
        [ 1],
        [25],
        [14]],

       [[23],
        [ 1],
        [12],
        ...,
        [25],
        [14],
        [11]],

       ...,

       [[ 7],
        [25],
        [ 1],
        ...,
        [24],
        [24],
        [ 1]],

       [[25],
        [ 1],
        [24],
        ...,
        [24],
        [ 1],
        [15]],

       [[ 1],
        [24],
        [14],
        ...,
        [ 1],
        [15],
        [25]]])

In [38]:
X = X/float(numberOfUniqueChars)
X

array([[[0.46666667],
        [0.36666667],
        [0.76666667],
        ...,
        [0.13333333],
        [0.03333333],
        [0.83333333]],

       [[0.36666667],
        [0.76666667],
        [0.03333333],
        ...,
        [0.03333333],
        [0.83333333],
        [0.46666667]],

       [[0.76666667],
        [0.03333333],
        [0.4       ],
        ...,
        [0.83333333],
        [0.46666667],
        [0.36666667]],

       ...,

       [[0.23333333],
        [0.83333333],
        [0.03333333],
        ...,
        [0.8       ],
        [0.8       ],
        [0.03333333]],

       [[0.83333333],
        [0.03333333],
        [0.8       ],
        ...,
        [0.8       ],
        [0.03333333],
        [0.5       ]],

       [[0.03333333],
        [0.8       ],
        [0.46666667],
        ...,
        [0.03333333],
        [0.5       ],
        [0.83333333]]])

In [39]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [41]:
model = Sequential()
#Since we know the shape of our Data we can input the timestep and feature data
#The number of timestep sequence are dealt with in the fit function
model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2])))
model.add(Dropout(0.2))
#number of features on the output
model.add(Dense(y.shape[1], activation='softmax'))



In [42]:
model.compile(loss='categorical_crossentropy', optimizer='adam')


In [43]:
model.fit(X, y, epochs=5, batch_size=128)


Epoch 1/5
1760/1760 [==============================] - 10s 5ms/step - loss: 3.1818
Epoch 2/5
1760/1760 [==============================] - 7s 4ms/step - loss: 3.0167
Epoch 3/5
1760/1760 [==============================] - 7s 4ms/step - loss: 3.0031
Epoch 4/5
1760/1760 [==============================] - 7s 4ms/step - loss: 3.0074
Epoch 5/5
1760/1760 [==============================] - 10s 6ms/step - loss: 2.9919


In [ ]:
model.save_weights("Othello.hdf5")
#model.load_weights("Othello.hdf5")

In [44]:
randomVal = np.random.randint(0, len(charX)-1)


In [45]:
randomVal

1364

In [46]:
randomStart = charX[randomVal]
randomStart

[23,
 11,
 3,
 1,
 15,
 2,
 1,
 12,
 7,
 15,
 25,
 14,
 3,
 1,
 2,
 25,
 28,
 7,
 24,
 1,
 24,
 25,
 23,
 7,
 19,
 13,
 11,
 3,
 1,
 2,
 25,
 28,
 7,
 24,
 1,
 21,
 7,
 24,
 24,
 15,
 19,
 13,
 1,
 24,
 25,
 23,
 7,
 19,
 13,
 11,
 6,
 0,
 2,
 25,
 28,
 7,
 24,
 1,
 21,
 15,
 25,
 15,
 12,
 26,
 17,
 3,
 1,
 2,
 25,
 28,
 7,
 24,
 1,
 28,
 20,
 19,
 10,
 23,
 20,
 26,
 24,
 1,
 21,
 15,
 25,
 15,
 12,
 26,
 17,
 5,
 0,
 24,
 14,
 11,
 1,
 28,
 15,
 24,
 14,
 11]

In [49]:
for i in range(500):
    x = np.reshape(randomStart, (1, len(randomStart), 1))
    x = x/float(numberOfUniqueChars)
    pred = model.predict(x)
    index = np.argmax(pred)
    randomStart.append(index)
    randomStart = randomStart[1: len(randomStart)]


In [50]:
print("".join([idsForChars[value] for value in randomStart]))